### ISSUE TITLE
Not working lvz.de

### ISSUE THREAD

**Issue by Yasty25** [hazuser/Hazuser99#2]
Hi!

Is it not working on lvz.de

gretings!

**Comment by hazuser** [comment]
patched, just update via TM or GM
Greetings

**Comment by Yasty25** [comment]
Hi! 
Since a few days it doesn't work anymore. lvz.de

Thanks for your support!

**Comment by crozeiro1** [comment]
> Hi! Since a few days it doesn't work anymore. lvz.de
> 
> Thanks for your support!

I checked that and couldn't verify a non-functionality. Are you using v0.45?

**Comment by Yasty25** [comment]
Yes, I have the 0.45
I tried it on two computers, the paywall comes on both.

**Comment by crozeiro1** [comment]
tested, for some reason it doen't work in chrome+tampermonkey.
Try using FF, until i found a fix for this.

**Comment by hazuser** [comment]
fixed, please verify, it was some tricky

**Comment by hazuser** [comment]
new Version 0.47, needed to clear cache to get Tamper get the update :(

**Comment by Yasty25** [comment]
Yes! Is working! Thanks!!! 👍
