### ISSUE TITLE
not working lvz.de

### ISSUE THREAD

**Issue by Yasty25** [hazuser/Hazuser99#4]
Hi!

Ich glaube du sprichst deutsch ;-)
lvz.de zumindest hat wieder an der paywall geschraubt. Nach dem laden der paywall Seite wird diese dann plötzlich blank. Man sieht nur das sie kurz geladen wird und dann ist alles weis.

Grüße!

**Comment by Yasty25** [comment]
Ich hab jetzt mal diese URL blockiert, dann gehts wieder: https://www.lvz.de/pf/dist/engine/react.js?d=136

**Comment by Yasty25** [comment]
Geht aber auch nur halb, man sieht auf der Startseite nur verschwommene Bilder der Artikel :-D

**Comment by hazuser** [comment]
hab es eben getestet unter Chrome/FF und es funktioniert. 
Hast du v 0.49 installiert?
Welchen Browser+Version nutzt du?

**Comment by Yasty25** [comment]
Hi! Jetzt geht es wieder plötzlich. Ging im Chrome neuste Version nicht. Also alles gut erst mal :-) Danke für deinen Support!
